language: java
jdk: 
  - oraclejdk15
sudo: false
cache:
  directories:
  - $HOME/.m2
before_install:
  - chmod +x mvnw
after_success:
  - mvn clean test jacoco:report coveralls:report
script: ./mvnw clean package